* セットアップ

** ソフトウェアのインストール

*** JDK

- JDK8

https://adoptopenjdk.net/


*** IDE

- IntelliJ Community Edition

が、任意のIDEを使用してよい（Eclipseなど）。

https://www.jetbrains.com/idea/

*** ビルドツール

- Maven 3.3.9(or later)

IntelliJを使用する場合、上記バージョンが組み込まれている。

*** SCM

**** GitHub

- GitHubのアカウントを作成すること。
- Collaboratorに登録するので、アカウント名を連絡すること。
  - (forkは使わないことにした)

**** Git

プロキシ経由で使用する場合は以下の設定を行う。

[[https://qiita.com/sambatriste/items/98f79cad3de9782f65b6][プロキシ内/外両方のGitリポジトリにアクセスする設定]]

* プロジェクト設定

** Git

#+BEGIN_SRC sh
git clone https://github.com/sambatriste/webstudy.git
#+END_SRC

** Webアプリケーションの起動
以下のコマンドでアプリケーションサーバ(Jetty)がポート7373で起動する。

#+BEGIN_SRC sh
mvn jetty:run
#+END_SRC

http://localhost:7373/hello
にアクセスする。

** DBマイグレーション

[[https://flywaydb.org/][Flyway]]を使用してDBマイグレーションを行う。

#+BEGIN_SRC sh
mvn flyway:migrate
#+END_SRC

単体テスト用のデータベースを設定する場合、プロファイル(unit-test)を指定する。
#+BEGIN_SRC sh
mvn -P ut-db flyway:migrate
#+END_SRC

元に戻すには、以下のコマンドを実行する。

#+BEGIN_SRC sh
mvn flyway:clean
#+END_SRC

** データベース参照(H2 Console)

データベースには[[http://www.h2database.com/][H2 Database]]を使用する。

データベースを参照するには、以下のコマンドを実行する。

#+BEGIN_SRC sh
mvn exec:java
#+END_SRC

（たぶん使う必要はないが）単体テスト用のデータベースを参照するには、以下のコマンドを実行する。

#+BEGIN_SRC sh
mvn -P ut-db exec:java
#+END_SRC

ブラウザに画面がうまく表示されない場合、URLのIPアドレスをlocalhostに書き換えてみる。

#+BEGIN_EXAMPLE
http://172.30.22.96:62642/  --> http://localhost:62642/
#+END_EXAMPLE

** データベースアクセス

データベースアクセスフレームワークには[[https://doma.readthedocs.io/][Doma2]]を使用する。

*** アノテーションプロセッサ

Doma2はアノテーションプロセッサを使用する。
コンパイル実行時に、アノテーションが付与されたクラスに対して操作を行う。
（インタフェースに対して、その実装クラスを自動生成する等）

**** アノテーションプロセッサの確認

IntelliJでアノテーションプロセッサを有効にするには以下の手順を行う。

アノテーションプロセッサが有効となっていること確認する。
Preferencesを開く。

- Build, Execution, Deployment
  - Compiler
    - Annotation Processors
- Maven default annotation processors profile
- Enable annotation processingをオン
- Obtain processors from project classpathを選択
- Store generated source relative to で Module content root を選択

**** 自動生成されたソースを有効にする

自動生成されたソースを有効にするには以下の手順を行う。

まずビルドを一度実行する。（自動生成出力先ディレクトリを作成するため）

Project Structureを開く。

- Project Settings
  - Module
    - WebStudy
- sourcesタブ
- target/generated-sources/annotationsをSourcesに設定
- target/generated-test-sources/test-annotationsをTestsに設定

*** Doma Support Plugin

IntelliJ用プラグインをインストールする。

- https://github.com/siosio/DomaSupport/releases
  - https://github.com/siosio/DomaSupport/releases/download/0.10/DomaSupport-IC.jar
